### ISSUE TITLE
wrong join clause for association

### ISSUE THREAD

**Issue by psfung** [quintans/goSQL#1]
Following your example, I try joining book with both publisher and book_bin associations:
```go
store.Query(BOOK).
    All().
    Inner(BOOK_A_PUBLISHER).
    Inner(BOOK_A_BOOK_BIN).
    Fetch().
    Where(BOOK_C_ID.Matches(1)).
    SelectTree(&book)
```
There is a book in my DB, but it doesn't return any result. From the debug log,

```sql
SELECT t0.`PUBLISHER_ID` AS t0_PublisherId,
    t0.`ID` AS t0_Id, t0.`VERSION` AS t0_Version,
    t0.`NAME` AS t0_Name, t0.`PRICE` AS t0_Price,
    t0.`PUBLISHED` AS t0_Published, t0_j1.`ID` AS t0_j1_Id,
    t0_j1.`VERSION` AS t0_j1_Version, t0_j1.`NAME` AS t0_j1_Name,
    t0_j2.`ID` AS t0_j2_Id, t0_j2.`VERSION` AS t0_j2_Version,
    t0_j2.`HARDCOVER` AS t0_j2_Hardcover
FROM `BOOK` t0 INNER JOIN `PUBLISHER` t0_j1 ON t0.`PUBLISHER_ID` = t0_j1.`ID`
    INNER JOIN `BOOK_BIN` t0_j2 ON t0_j1.`ID` = t0_j2.`ID`
WHERE t0.`ID` = :t0_R1
```

The join clause for BOOK_BIN is wrong. It should be corrected to
ON t0.`ID` = t0_j2.`ID`

**Comment by quintans** [comment]
Hi,
Your query maps the following 
BOOK -> PUBLISHER -> BOOK_BIN
but this is not valid, because you cannot reach BOOK_BIN from PUBLISHER. 
You have to use ```Fetch()``` to reset the branch back to the main table, in this case BOOK, to map the following:
PUBLISHER <- BOOK -> BOOK_BIN

For that you use the query:  

```go
store.Query(BOOK).
    All().
    Inner(BOOK_A_PUBLISHER).
    Fetch(). // the missing fetch
    Inner(BOOK_A_BOOK_BIN).
    Fetch().
    Where(BOOK_C_ID.Matches(1)).
    SelectTree(&book)
```

Still, this query does not bring any results. Perhaps you want to make an outer join?

**Comment by quintans** [comment]
Just wanted to clarify my last comment. The query will not return any rows, assuming that the table BOOK_BIN is empty (the tests did not populate the table).
Meanwhile I have altered the tests so that the BOOK_BIN is populated and therefore the above query will yield results.

**Comment by psfung** [comment]
The readme has been updated to show the usage of multiple join and the purpose of calling Fetch(). Well done.
